### PR TITLE
Introduce Words stats parameters to SDK

### PR DESCRIPTION
**Pull request by rvanlaak**
Adds resolver to expose the 'includeTextInShapes' and 'includeFootnotes' parameters to the SDK.

### CODE REVIEW

**Comment by rvanlaak** [comment]
ping @masood-anwer

**Comment by imranwar** [comment]
Salam Masood,

I am on it now!

On Thu, Dec 24, 2015 at 3:33 PM, Richard van Laak <notifications@github.com>
wrote:

> Adds resolver to expose the 'includeTextInShapes' and 'includeFootnotes'
> parameters to the SDK.
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/asposeforcloud/Aspose_Cloud_SDK_For_PHP/pull/40
> Commit Summary
>
>    - Introduce Words stats parameters to SDK
>
> File Changes
>
>    - *M* src/Aspose/Cloud/Words/Document.php
>    <https://github.com/asposeforcloud/Aspose_Cloud_SDK_For_PHP/pull/40/files#diff-0>
>    (27)
>
> Patch Links:
>
>    -
>    https://github.com/asposeforcloud/Aspose_Cloud_SDK_For_PHP/pull/40.patch
>    -
>    https://github.com/asposeforcloud/Aspose_Cloud_SDK_For_PHP/pull/40.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/asposeforcloud/Aspose_Cloud_SDK_For_PHP/pull/40>.
>



-- 
Regards
Imran Anwar

**Comment by imranwar** [comment]
@rvanlaak , Thanks for you interest in our SDKs  your pull request have been merged.

We are in a process of introducing our SDKs product wise so please look at our following product wise repos as well:
https://github.com/asposewords/Aspose_Words_Cloud/tree/master/SDKs

Thanks!

**Comment by rvanlaak** [comment]
Hi @imranwar I already see a big problem with that repo, it contains the SDKs of all different sorts of languages. That definately is a no-go.

We think you should create a new `2.0` branch in this repository and work on the new version in that specific branch. 

This way the new SDK won't be usable in the Symfony bundle https://github.com/asposeforcloud/asposesymfony

**Comment by imranwar** [comment]
Hi @rvanlaak ,

As I already said we are in a process of moving our SKDs to product wise, We have noted your suggestion and will inform you once we will have a solution of this problem, Thanks!

**Pull request merged**
