### PR TITLE
Added File class (for use with storage endpoints) with getFile and co…

### PR DESCRIPTION
**Pull request by jasonpranevicius**
…pyFile methods

### CODE REVIEW

**Comment by farooqsheikhpk** [comment]
@jasonpranevicius

Please feel free to use our latest and improved product-wise Aspose Cloud SDKs for PHP. 

https://packagist.org/search/?q=aspose

- Storage  https://github.com/asposetotal/Aspose-Cloud-Storage-SDK-For-PHP
- Words  https://github.com/aspose-words/Aspose.Words-Cloud-SDK-for-PHP
and so on. 

Please feel free to reach me for any question related to it. 

Regards,
Farooq Sheikh

**Comment by rvanlaak** [comment]
Why would you even split the single SDK in separate SDKs? Probably they all have the same boilerplate code for doing the requests?

Would be better to make PRs for this repo, and release a new major version if it is stable.

**Comment by farooqsheikhpk** [comment]
@rvanlaak 

Aspose has 9 cloud products APIs at this time. Each product is independent with each other. It means it has its name and brand. 

The Single Aspose Cloud SDK For PHP has following limitations
1. It has limited products APIs coverage. 
2. As all products apis are merged into single SDK; therefore it confuses the end user if he/she interested in use 1 or 2 Aspose Products APIs.

After detailed analysis management has finally decided to switch over to product-wise SDKs with following improvement 

 1. Use some mechanism to generate SDKs instead of manual code writing. We use swagger Autogen tool for this purpose. 
2. Make sure generated SDKs code are free from error prone. We wrote test cases for each generated APIs. 
3. Make sure generated SDKs must have 100% API coverage. 
4. Make sure generated SDKs must have tendency to upgrade with latest changes and APIs with minimum human effort. 

Hope this will cover most of your questions. I would again suggest to review new SDKs and give your valuable feedback.

Looking forward to see your remarks. 

Regards,
Farooq Sheikh

**Comment by rvanlaak** [comment]
The Aspose cloud product has one API, which has all features. Not nine products, as you assume. There are nine offline components (Java, .net) , the cloud API is just a wrapper on top of all of them and makes this one single product.

So only being interested in one product does not apply, anything is and should be available in the API and a SDK should represent the entire product. So, represent the cloud product. The SDK users (developers) should be able to decide themselves what classes they use, you should not make that decision for them. You think Google is letting it's developer install separate repos / libraries for each project they want to use? https://github.com/google/google-api-php-client-services

Developers should not have to configure nine times the same API key over and over again. Probably there will be conflicting namespaces too if multiple SDKs are used. Or, how should developers catch exceptions if they all have their own namespace? 
This brings me with the limited products API coverage, this is completely Aspose's fault by not maintaining the SDK properly. Newly released API features should always be released in the SDK too. This is not a problem you should confront the developers that use the SDK with. The last couple of months I've submitted quite some PRs because features were missing.

So please reconsider your decision, I think the analysis results you point out are really good but the decisions that are made because of this do not reflect them. Basically a new branch with proper [`semver`](http://semver.org/)-ing would have solved all of this. :+1:

**Comment by farooqsheikhpk** [comment]
@rvanlaak 

Thanks for sharing your thoughts. Some of your points are valid regarding Aspose.Total SDK usage. I will raise this issue with my lead and get back to you soon. 

Regards,
Farooq Sheikh

**Comment by jasonpranevicius** [comment]
I'm confused as to why you would want to split them, this repo seems fine to me just a little outdated. The code structure seems to work well and makes sense placing them all together. 

It may be worth letting developers know that they're working on\using a now deprecated repository.

**Comment by rvanlaak** [comment]
@jasonpranevicius I agree :wink: , their analysis results seems great to me:

> * Use some mechanism to generate SDKs instead of manual code writing. We use swagger Autogen tool for this purpose.
> * Make sure generated SDKscode are free from error prone. We wrote test cases for each generated SDK.
> * Make sure generated SDK must have 100% API coverage.
> * Make sure generated SDK must have tendency to upgrade with latest changes and APIs with minimum human effort.

But this does not suggest making millions of repositories and separate SDKs :+1:

**Comment by farooqsheikhpk** [comment]
@rvanlaak @jasonpranevicius 
Thank you for your feedback, we will get back to you with further updates.

**Pull request merged**
